const equipmentData = [
  {
    building: {
      CID: 19,
      ClientName: "Clockworks Analytics",
      Address: "1111 Test Ave",
      ArchivePlan: 0,
      ArchiveRenewalDate: null,
      ArchiveStartDate: null,
      AutomatedPriorityDailyEmails: false,
      AutomatedPriorityMonthlyEmails: false,
      AutomatedPriorityWeeklyEmails: false,
      BID: 18175,
      BuildingClassDescription: null,
      BuildingClassID: 3,
      BuildingClassName: "Office",
      BuildingGroupID: null,
      BuildingGroupName: null,
      BuildingName: "Digital Building Demo",
      BuildingOwnership: "Property Management Company",
      BuildingShape: "Rectangle with Courtyard",
      BuildingTypeDescription: null,
      BuildingTypeID: 45,
      BuildingTypeName: "Office",
      UnitID: 19,
      City: "Acworth",
      UnitName: "Clockworks Analytics",
      Computers: 0,
      CountryAlpha2Code: "US",
      CountryName: "United States",
      Description: null,
      EnergyBureauContactName: null,
      EnergyBureauService: false,
      EnergyBureauServiceFrequency: null,
      EnergyBureauServiceHours: null,
      EnvelopeGlassPercentage: 25,
      Floors: 50,
      ImageExtension: "",
      InternalNotes: null,
      IsActive: true,
      IsVisible: true,
      LCID: 1033,
      Latitude: 34.03856,
      Location: null,
      Longitude: -84.6904,
      MainCoolingSystem: "Chillers",
      MainHeatingSystem: "District Services",
      MaxPointLimit: 10000,
      Occupants: 15000,
      OperatingHours: 24,
      Phone: "4045555555",
      PrimaryContactEmail: null,
      PrimaryContactName: null,
      PrimaryContactPhone: null,
      RoofConstruction: "Built-Up",
      SASLink: null,
      SASReferenceID: null,
      SettingsDateModified: "2022-09-07T01:02:29.617",
      SetupContactName: null,
      Area: 20000,
      StateID: 3464,
      StateName: "Georgia",
      SubscriptionPlan: 12,
      SubscriptionRenewalDate: null,
      SubscriptionStartDate: "2022-08-01T00:00:00",
      TimeZone: "Eastern Standard Time",
      UnitSystem: false,
      WeatherFileName: "USA_GA_Atlanta-Hartsfield-Jackson.Intl.AP.722190_TMY3",
      WeatherFileGFID: 125,
      WebsiteLink: null,
      YearBuilt: 2022,
      Zip: "30101",
      TimeZoneDisplayName: "(UTC-05:00) Eastern Time (US & Canada)",
      WeatherFileDisplayName:
        "USA_GA_Atlanta-Hartsfield-Jackson.Intl.AP.722190_TMY3",
      BuildingType: null,
      BuildingBuildingVariables: null,
      Equipment: null,
      EquipmentPoints: null,
      EquipmentTypes: null,
      EquipmentClasses: null,
      TaskRecords: null,
      Points: null,
      UpdateFields: [],
      DateCreated: "2022-08-01T14:45:29.793",
      DateModified: "2022-09-07T01:02:29.537",
    },
    equipClasses: [
      {
        EquipmentClassID: 36,
        EquipmentClassName: "Air Handler",
        EquipmentClassDescription: "Air Handling Equipment",
        IsGroup: true,
        EquipmentTypes: null,
        UpdateFields: null,
        DateCreated: "2012-10-18T14:40:07.263",
        DateModified: "2012-10-23T02:07:40.173",
      },
      {
        EquipmentClassID: 4,
        EquipmentClassName: "Chiller",
        EquipmentClassDescription: null,
        IsGroup: true,
        EquipmentTypes: null,
        UpdateFields: null,
        DateCreated: "2010-07-23T16:07:29.07",
        DateModified: "2010-07-23T16:16:57.593",
      },
      {
        EquipmentClassID: 27,
        EquipmentClassName: "Cooling System",
        EquipmentClassDescription:
          "Cooling systems, such as cooling plants, chilled or condenser water loops, and cooling towers",
        IsGroup: true,
        EquipmentTypes: null,
        UpdateFields: null,
        DateCreated: "2012-10-02T18:07:38.307",
        DateModified: "2012-10-02T18:10:00.197",
      },
      {
        EquipmentClassID: 5,
        EquipmentClassName: "Fan",
        EquipmentClassDescription: null,
        IsGroup: true,
        EquipmentTypes: null,
        UpdateFields: null,
        DateCreated: "2010-07-23T16:07:35.493",
        DateModified: "2010-07-23T16:17:18.04",
      },
      {
        EquipmentClassID: 13,
        EquipmentClassName: "Heat Exchanger",
        EquipmentClassDescription: null,
        IsGroup: true,
        EquipmentTypes: null,
        UpdateFields: null,
        DateCreated: "2010-12-10T10:01:11.153",
        DateModified: "2010-12-10T10:01:11.143",
      },
      {
        EquipmentClassID: 35,
        EquipmentClassName: "Heat Recovery System",
        EquipmentClassDescription: null,
        IsGroup: true,
        EquipmentTypes: null,
        UpdateFields: null,
        DateCreated: "2012-10-17T21:11:21.55",
        DateModified: "2012-10-17T21:11:21.7",
      },
      {
        EquipmentClassID: 28,
        EquipmentClassName: "Heating System",
        EquipmentClassDescription:
          "Heating systems, such as heating plant and hot water loops",
        IsGroup: true,
        EquipmentTypes: null,
        UpdateFields: null,
        DateCreated: "2012-10-02T18:10:27.677",
        DateModified: "2012-10-02T18:10:28.697",
      },
      {
        EquipmentClassID: 29,
        EquipmentClassName: "Outdoor Conditions",
        EquipmentClassDescription: null,
        IsGroup: true,
        EquipmentTypes: null,
        UpdateFields: null,
        DateCreated: "2012-10-17T14:21:19.64",
        DateModified: "2012-10-17T14:21:20.21",
      },
      {
        EquipmentClassID: 3,
        EquipmentClassName: "Pump",
        EquipmentClassDescription: null,
        IsGroup: true,
        EquipmentTypes: null,
        UpdateFields: null,
        DateCreated: "2010-07-23T16:06:53.217",
        DateModified: "2010-07-23T16:17:26.993",
      },
      {
        EquipmentClassID: 34,
        EquipmentClassName: "Utilities",
        EquipmentClassDescription:
          "This class contains utility metering equipment, such as whole building electric, gas, steam or chilled water meters or submeters.",
        IsGroup: true,
        EquipmentTypes: null,
        UpdateFields: null,
        DateCreated: "2012-10-17T21:04:00.91",
        DateModified: "2012-10-17T21:04:02.713",
      },
      {
        EquipmentClassID: 31,
        EquipmentClassName: "Ventilation System",
        EquipmentClassDescription: null,
        IsGroup: true,
        EquipmentTypes: null,
        UpdateFields: null,
        DateCreated: "2012-10-17T14:43:40.057",
        DateModified: "2012-10-17T14:43:41.847",
      },
      {
        EquipmentClassID: 9,
        EquipmentClassName: "Zone Equipment",
        EquipmentClassDescription:
          "This class includes zone level terminal units such as VAV boxes, fan powered boxes, fan coil units, packaged heat pumps, chilled beams, etc.",
        IsGroup: true,
        EquipmentTypes: null,
        UpdateFields: null,
        DateCreated: "2010-10-27T17:36:30.78",
        DateModified: "2013-11-22T23:51:04.603",
      },
    ],
  },
];